# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy Client (GitHub Pages)

on:
  push:
    branches: [ "master" ]
    
permissions:
  contents: write

jobs:
  build-and-deploy-to-github-pages:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Publish
      run: dotnet publish src/Client/Client.csproj -c Release -o release --nologo
      
    # changes the base-tag in index.html from '/' to 'error-communication-training-demo' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to error-communication-training-demo
      run: sed -i 's/<base href="\/" \/>/<base href="\/error-communication-training-demo\/" \/>/g' release/wwwroot/index.html

    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v3.1.0
      with:
        # Build directory to deploy
        build_dir: release/wwwroot
        # Allow Jekyll to build your site
        jekyll: false
        # Enable verbose output
        verbose: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
